# Generated by Django 3.1.2 on 2020-11-29 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=400, null=True)),
                ('seen', models.BooleanField(default=False)),
                ('date', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
